import "./pwa-register.js?v=20260812-node-vector-boot-3";
import * as THREE from "three";
import { setupUpload } from "./core/upload.js";
import { chooseSaveFormat, saveScene } from "./core/save.js?v=20260811-save-singleton-1";
import { loadScene } from "./core/load.js";
import { setupExporter } from "./core/exporter.js";
import { setupImporter } from "./core/importer.js";
import { setupCopyPaste } from "./core/copyPaste.js";
import { setupDuplicate } from "./core/duplicate.js";
import { toggleSnap, setupTransform, setTransformMode, setTransformSpace, toggleTransformSpace, getTransformSpace, isDraggingTransform } from "./core/transform.js?v=20260812-transform-axis-fix-4";
import { initNumericTransform } from "./core/numericTransform.js";
import { undo, redo, canUndo, canRedo } from "./core/history.js";
import { initScene, scene, renderer, camera, controls, createDefaultCube, grid, resetCamera, getFPS } from "./core/scene.js?v=20260811-runtime-fix";
import { focusObject } from "./core/focus.js";
import { setupDelete } from "./core/delete.js";
import { setupSelection, clearSelection, getSelected } from "./core/selection.js";
import { addObject, getObjects } from "./core/objectManager.js";
import { addToHierarchy, initHierarchy, rebuildHierarchy } from "./ui/hierarchy.js";
import { initInspector, updateInspector } from "./ui/inspector.js";
import { initSetFocusControl } from "./ui/setFocusControl.js";
import { initPivotControl } from "./ui/pivotControl.js";
import { initRocketPartPanel, toggleRocketPartMode } from "./ui/rocketPartPanel.js";
import { initAttachmentNodePanel } from "./ui/attachmentNodePanel.js";
import { initAttachmentNodeEditor } from "./rocket/attachmentNodes.js";
import { initNodeVectorRenderer } from "./rocket/nodeVectorRenderer.js?v=20260812-node-vector-render-2";
import { initMaterialLibrary } from "./core/materialLibrary.js";
import { initMaterialLibraryPanel } from "./ui/materialLibraryPanel.js";
import { createObject } from "./objects/factory.js";
import { groupSelected, ungroupSelected } from "./core/grouping.js";

const state = { transformMode: "translate", transformSpace: "world", lastStatus: "Ready", mobileSheet: null, device: getDeviceProfile() };
boot();

function boot() {
    installAdaptiveStyles();
    initScene();
    setupTransform(camera, renderer, scene, controls);
    setupSelection(renderer, camera, scene);
    initInspector();
    initSetFocusControl();
    initPivotControl();
    initRocketPartPanel(scene);
    initAttachmentNodeEditor(scene, renderer, camera);
    initAttachmentNodePanel();
    initNumericTransform();
    initNodeVectorRenderer(scene);
    initMaterialLibrary();
    initMaterialLibraryPanel();
    initHierarchy(scene);
    setupDelete(scene);
    setupDuplicate(scene);
    setupCopyPaste(scene);
    setupImporter(scene);
    setupExporter(scene);
    setupUpload(scene);
    const defaultCube = createDefaultCube();
    addToHierarchy(defaultCube);
    updateInspector(null);
    bindUI();
    bindEditorEvents();
    bindKeyboard();
    bindResponsiveLayer();
    requestAnimationFrame(() => initMaterialLibraryPanel());
    updateObjectCount();
    updateHistoryButtons();
    syncTransformSpaceUI();
    setStatus("Ready");
}
