import * as THREE from "three";
import { addObject, clearObjects } from "./objectManager.js";
import { rebuildHierarchy } from "../ui/hierarchy.js";
import { migrateToRKPv2 } from "./rkpMigration.js";
import { validateRKP } from "./rkpValidator.js";
const ACCEPT=".rkp,.json,.obj,.gltf,.glb,.stl,.fbx,.dae,.3ds,.ply,.csv,.txt,application/json,model/gltf+json,model/gltf-binary,text/plain";
export function loadScene(scene){const input=document.createElement("input");input.type="file";input.accept=ACCEPT;input.onchange=e=>{const file=e.target.files?.[0];if(file)openProjectFile(scene,file);input.value=""};input.click()}
export async function openProjectFile(scene,file){if(!file)return false;const ext=file.name.split(".").pop()?.toLowerCase();try{if(ext==="rkp"||ext==="json")return await openJSONProject(scene,file);if(ext==="obj")return await openLoader(scene,file,"OBJLoader");if(ext==="gltf"||ext==="glb")return await openGLTF(scene,file);if(ext==="stl")return await openLoader(scene,file,"STLLoader");if(ext==="fbx")return await openLoader(scene,file,"FBXLoader");if(ext==="dae")return await openLoader(scene,file,"ColladaLoader");if(ext==="3ds")return await openLoader(scene,file,"TDSLoader");if(ext==="ply")return await openLoader(scene,file,"PLYLoader");throw new Error(`Unsupported file type: .${ext}`)}catch(error){console.error("Import failed:",error);window.dispatchEvent(new CustomEvent("editor:status",{detail:`Import failed: ${error.message||file.name}`}));return false}}
async function openJSONProject(scene,file){const asset=migrateToRKPv2(JSON.parse(await file.text())),validation=validateRKP(asset);if(!validation.valid){const error=new Error(validation.errors.slice(0,5).map(i=>`${i.code}: ${i.message}`).join("; "));throw error}const roots=Array.isArray(asset.objects)?asset.objects:[];clearObjects(scene);roots.forEach(data=>restoreObject(scene,scene,data));rebuildHierarchy();announce(file,"RKP",roots.length,{assetId:asset.metadata.id,assetType:asset.metadata.assetType,version:asset.version});return true}
async function openGLTF(scene,file){const{GLTFLoader}=await import("three/addons/loaders/GLTFLoader.js"),loader=new GLTFLoader(),result=await new Promise((resolve,reject)=>loader.parse(await file.arrayBuffer(),"",resolve,reject));return addImportedRoot(scene,result.scene,file,"glTF")}
async function openLoader(scene,file,name){const module=await import(`three/addons/loaders/${name}.js`),Loader=module[name];if(!Loader)throw new Error(`${name} unavailable`);const loader=new Loader(),source=name==="STLLoader"||name==="PLYLoader"?await file.arrayBuffer():await file.text(),parsed=loader.parse(source),root=parsed.isObject3D?parsed:new THREE.Mesh(parsed,new THREE.MeshStandardMaterial({color:0xb7c0ca,roughness:.6}));return addImportedRoot(scene,root,file,name.replace("Loader",""))}
function addImportedRoot(scene,root,file,format){clearObjects(scene);root.name=file.name.replace(/\.[^.]+$/i,"")||"Imported Model";root.userData.editorObject=true;root.traverse(o=>{o.userData.editorObject=true;if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(root);rebuildHierarchy();announce(file,format,root.children?.length||1);return true}
function restoreObject(scene,parent,data){if(!data)return null;let object;if(data.kind==="Group"||data.type==="Group"){object=new THREE.Group();object.userData.selectable=true}else{const geometry=createGeometry(data.type);if(!geometry)return null;const materials=(data.materials||[]).map(createMaterial);const material=materials.length===1?materials[0]:materials.length?materials:new THREE.MeshStandardMaterial({color:0xffffff,roughness:.65});object=new THREE.Mesh(geometry,material);object.castShadow=object.receiveShadow=true;object.userData.selectable=true}object.name=data.name||"Object";object.visible=data.visible??true;object.position.fromArray(normalizeVector(data.position,[0,0,0]));object.rotation.set(...normalizeVector(data.rotation,[0,0,0]));object.scale.fromArray(normalizeVector(data.scale,[1,1,1]));object.userData.editorObject=true;Object.assign(object.userData,data.userData||{});parent.add(object);addObject(scene,object);(data.children||[]).forEach(child=>restoreObject(scene,object,child));return object}
function createMaterial(data){const m=new THREE.MeshStandardMaterial({color:data?.color??0xffffff,metalness:data?.metalness??0,roughness:data?.roughness??1,opacity:data?.opacity??1,transparent:data?.transparent??false,depthWrite:data?.depthWrite??((data?.opacity??1)>=1),wireframe:data?.wireframe??false,side:data?.side??THREE.FrontSide,emissive:data?.emissive??0,emissiveIntensity:data?.emissiveIntensity??1});m.name=data?.name||"";m.flatShading=!!data?.flatShading;const slots=data?.textureSlots||{};m.userData.textureSlots=slots;m.userData.textureTransform=data?.textureTransform||{repeatX:1,repeatY:1,offsetX:0,offsetY:0,rotation:0};for(const [key,info] of Object.entries(slots)){const prop={baseColor:"map",normal:"normalMap",roughness:"roughnessMap",metalness:"metalnessMap",ao:"aoMap",height:"displacementMap",emissive:"emissiveMap",alpha:"alphaMap"}[key];if(!prop||!info?.dataUrl)continue;try{new THREE.TextureLoader().load(info.dataUrl,t=>{t.colorSpace=key==="baseColor"||key==="emissive"?THREE.SRGBColorSpace:THREE.NoColorSpace;t.flipY=false;t.wrapS=t.wrapT=THREE.RepeatWrapping;applyUV(t,m.userData.textureTransform);m[prop]=t;if(key==="alpha"){m.transparent=true;m.depthWrite=false}m.needsUpdate=true})}catch{}}if(data?.baseTextureData&&!slots.baseColor)m.userData.baseTextureData=data.baseTextureData;m.needsUpdate=true;return m}
function applyUV(t,x={repeatX:1,repeatY:1,offsetX:0,offsetY:0,rotation:0}){t.repeat.set(Number(x.repeatX)||1,Number(x.repeatY)||1);t.offset.set(Number(x.offsetX)||0,Number(x.offsetY)||0);t.rotation=THREE.MathUtils.degToRad(Number(x.rotation)||0);t.center.set(.5,.5)}
function createGeometry(type){switch(type){case"BoxGeometry":return new THREE.BoxGeometry(1,1,1);case"SphereGeometry":return new THREE.SphereGeometry(.5,32,20);case"CylinderGeometry":return new THREE.CylinderGeometry(.5,.5,2,32);case"ConeGeometry":return new THREE.ConeGeometry(.5,1.5,32);case"PlaneGeometry":return new THREE.PlaneGeometry(5,5);case"OctahedronGeometry":return new THREE.OctahedronGeometry(.5);case"TorusGeometry":return new THREE.TorusGeometry(.5,.2,16,64);default:return null}}function normalizeVector(v,f){return Array.isArray(v)&&v.length>=3?[Number(v[0])||0,Number(v[1])||0,Number(v[2])||0]:v&&typeof v==="object"?[Number(v.x)||0,Number(v.y)||0,Number(v.z)||0]:f}function announce(file,format,count,extra={}){window.dispatchEvent(new CustomEvent("editor:project-opened",{detail:{fileName:file.name,format,objectCount:count,...extra}}));window.dispatchEvent(new CustomEvent("editor:status",{detail:`Imported ${file.name}`}))}
