import * as THREE from "three";
import { getInspectorObject, refreshInspector } from "../ui/inspector.js";

const SLOTS=[
["baseColor","Base Color","map","PNG/JPG/WebP","2048×2048","Color / Albedo"],
["normal","Normal","normalMap","PNG/WebP","2048×2048","Tangent-space normal"],
["roughness","Roughness","roughnessMap","PNG/WebP","1024×1024","Grayscale: white = rough"],
["metalness","Metallic","metalnessMap","PNG/WebP","1024×1024","Grayscale: white = metal"],
["ao","Ambient Occlusion","aoMap","PNG/WebP","1024×1024","Grayscale contact shadows"],
["height","Height","displacementMap","PNG/WebP","1024×1024","Grayscale height map"],
["emissive","Emissive","emissiveMap","PNG/JPG/WebP","1024×1024","Glowing areas"],
["alpha","Alpha","alphaMap","PNG/WebP","1024×1024","Transparency mask"]
];
const PROFILES={BoxGeometry:["Box / Prop","2048×2048","Square tileable texture"],SphereGeometry:["Sphere / Planet","2048×2048","Equirectangular/spherical UV texture"],CylinderGeometry:["Cylinder","2048×2048","Square texture; keep vertical details crisp"],ConeGeometry:["Cone","2048×2048","Square texture with top-detail padding"],PlaneGeometry:["Plane / Decal","2048×2048","PNG/WebP if transparency is needed"],TorusGeometry:["Torus","2048×2048","Square seamless texture"],OctahedronGeometry:["Low-poly","1024×1024","1024 is usually enough for game assets"]};
const OBS="__mfTextureObserver";
export function initTextureSystem(){if(window[OBS])return;const panel=document.getElementById("inspectorContent");if(!panel)return;installStyles();const enhance=()=>{const section=[...panel.querySelectorAll(".section")].find(s=>s.querySelector?.(".file-input-label"));if(!section||section.querySelector(".mf-texture-system"))return;const object=getInspectorObject(),material=getMaterial(object);if(!material)return;(section.querySelector(".section-body")||section).appendChild(build(object,material));};window[OBS]=new MutationObserver(()=>requestAnimationFrame(enhance));window[OBS].observe(panel,{childList:true,subtree:true});enhance();}
function getMaterial(o){return o?.material?(Array.isArray(o.material)?o.material[0]:o.material):null;}
function build(object,material){const root=document.createElement("div");root.className="mf-texture-system";const p=PROFILES[object?.geometry?.type]||[object?.geometry?.type||"Custom mesh","2048×2048","Use 1024×1024 for small assets, 2048×2048 for hero assets"];root.innerHTML=`<div class="mf-ts-head"><div><b>Texture Set</b><span>Game-ready PBR texture slots</span></div><i>${p[0]}</i></div><div class="mf-ts-tip"><b>Recommended ${p[1]}</b><span>${p[2]}</span></div><div class="mf-ts-grid"></div><div class="mf-ts-uv-title">UV Transform</div><div class="mf-ts-uv"></div>`;SLOTS.forEach(s=>root.querySelector(".mf-ts-grid").appendChild(slot(material,s)));uv(root.querySelector(".mf-ts-uv"),material);return root;}
function slot(material,s){const [key,label,prop,types,size,hint]=s,wrap=document.createElement("div"),cur=material[prop];wrap.className="mf-ts-slot";const info=document.createElement("div");info.className="mf-ts-info";const thumb=document.createElement("div");thumb.className="mf-ts-thumb";if(cur?.image){const c=document.createElement("canvas");c.width=c.height=44;thumb.appendChild(c);try{c.getContext("2d").drawImage(cur.image,0,0,44,44)}catch{}}else thumb.textContent="＋";const text=document.createElement("div");text.innerHTML=`<b>${label}</b><span>${types}</span><small>Recommended ${size}</small>`;info.append(thumb,text);const actions=document.createElement("div");actions.className="mf-ts-actions";const choose=document.createElement("button");choose.textContent=cur?"Replace":"Select";const input=document.createElement("input");input.type="file";input.accept=key==="baseColor"||key==="emissive"?".png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp":".png,.webp,image/png,image/webp";input.hidden=true;choose.onclick=()=>input.click();input.onchange=async()=>{const f=input.files?.[0];if(!f)return;try{await apply(material,key,prop,f);refreshInspector();status(`${label} texture applied`)}catch(e){status(e.message||`Could not load ${f.name}`)}input.value=""};const clear=document.createElement("button");clear.textContent="Clear";clear.disabled=!cur;clear.onclick=()=>{material[prop]?.dispose?.();material[prop]=null;if(material.userData?.textureSlots)delete material.userData.textureSlots[key];material.needsUpdate=true;refreshInspector();status(`${label} texture cleared`)};actions.append(choose,clear,input);wrap.append(info,actions);wrap.title=hint;return wrap;}
async function apply(material,key,prop,file){if(file.size>12*1024*1024)throw new Error("Each texture must be 12 MB or smaller.");const data=await read(file),image=await imageLoad(data);if(image.width>8192||image.height>8192)throw new Error(`Maximum texture size is 8192×8192. Selected ${image.width}×${image.height}.`);const tex=new THREE.Texture(image);tex.colorSpace=key==="baseColor"||key==="emissive"?THREE.SRGBColorSpace:THREE.NoColorSpace;tex.flipY=false;tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.needsUpdate=true;material[prop]?.dispose?.();material[prop]=tex;material.userData=material.userData||{};material.userData.textureSlots=material.userData.textureSlots||{};material.userData.textureSlots[key]={dataUrl:data,name:file.name,width:image.width,height:image.height,bytes:file.size,type:file.type||"image/*"};if(key==="ao")uv2();applyUV(material,material.userData.textureTransform||{repeatX:1,repeatY:1,offsetX:0,offsetY:0,rotation:0});material.needsUpdate=true;}
function uv2(){const o=getInspectorObject(),uv=o?.geometry?.attributes?.uv;if(!uv||o.geometry.attributes.uv2)return;o.geometry.setAttribute("uv2",new THREE.BufferAttribute(uv.array.slice(),2));}
function uv(parent,material){const x={repeatX:1,repeatY:1,offsetX:0,offsetY:0,rotation:0,...(material.userData?.textureTransform||{})};[["Repeat X","repeatX",.01,32],["Repeat Y","repeatY",.01,32],["Offset X","offsetX",-10,10],["Offset Y","offsetY",-10,10],["Rotation°","rotation",-360,360]].forEach(([l,k,min,max])=>{const r=document.createElement("label");r.className="mf-ts-uv-field";r.innerHTML=`<span>${l}</span><input type="number" step=".01" min="${min}" max="${max}" value="${x[k]}">`;r.querySelector("input").onchange=e=>{x[k]=Math.min(max,Math.max(min,Number(e.target.value)||min));applyUV(material,x)};parent.appendChild(r)});const b=document.createElement("div");b.className="mf-ts-uv-buttons";const t=document.createElement("button");t.textContent="Tile 2×";t.onclick=()=>{x.repeatX=x.repeatY=2;applyUV(material,x);refreshInspector()};const r=document.createElement("button");r.textContent="Reset UV";r.onclick=()=>{x.repeatX=x.repeatY=1;x.offsetX=x.offsetY=x.rotation=0;applyUV(material,x);refreshInspector()};b.append(t,r);parent.appendChild(b);}
function applyUV(material,x){material.userData=material.userData||{};material.userData.textureTransform={...x};["map","normalMap","roughnessMap","metalnessMap","aoMap","displacementMap","emissiveMap","alphaMap"].forEach(k=>{const t=material[k];if(!t)return;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(x.repeatX,x.repeatY);t.offset.set(x.offsetX,x.offsetY);t.rotation=THREE.MathUtils.degToRad(x.rotation);t.center.set(.5,.5);t.needsUpdate=true})}
function read(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}function imageLoad(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error("Invalid or unreadable image."));i.src=src})}function status(s){window.dispatchEvent(new CustomEvent("editor:status",{detail:s}))}
function installStyles(){if(document.getElementById("mf-texture-style"))return;const s=document.createElement("style");s.id="mf-texture-style";s.textContent=`.mf-texture-system{margin-top:12px;padding-top:12px;border-top:1px solid #2b2f37}.mf-ts-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.mf-ts-head b{display:block;font-size:12px;color:#e8ebf0}.mf-ts-head span{display:block;font-size:9px;color:#7f8793;margin-top:2px}.mf-ts-head i{font-style:normal;font-size:8px;color:#aab1bd;border:1px solid #353a44;border-radius:4px;padding:4px 6px}.mf-ts-tip{padding:8px;background:#14171c;border:1px solid #2b3039;border-radius:5px;margin-bottom:8px}.mf-ts-tip b,.mf-ts-tip span{display:block}.mf-ts-tip b{font-size:10px;color:#cfd4dc}.mf-ts-tip span{font-size:9px;color:#777f8c;margin-top:2px}.mf-ts-grid{display:grid;gap:6px}.mf-ts-slot{display:flex;justify-content:space-between;gap:7px;align-items:center;padding:7px;border:1px solid #2d323b;border-radius:6px;background:#171a20}.mf-ts-info{display:flex;align-items:center;gap:7px;min-width:0}.mf-ts-info b,.mf-ts-info span,.mf-ts-info small{display:block}.mf-ts-info b{font-size:10px;color:#dfe3e9}.mf-ts-info span{font-size:8px;color:#7f8792}.mf-ts-info small{font-size:8px;color:#626a77;margin-top:2px}.mf-ts-thumb{width:38px;height:38px;flex:none;display:grid;place-items:center;border:1px solid #343944;border-radius:4px;background:#0f1115;color:#68717f;overflow:hidden}.mf-ts-thumb canvas{width:38px;height:38px}.mf-ts-actions{display:flex;gap:4px}.mf-ts-actions button,.mf-ts-uv-buttons button{height:27px;padding:0 7px;border:1px solid #363b45;border-radius:4px;background:#20242b;color:#bfc5ce;font-size:9px;cursor:pointer}.mf-ts-actions button:hover,.mf-ts-uv-buttons button:hover{background:#292e37;color:#fff}.mf-ts-actions button:disabled{opacity:.4}.mf-ts-uv-title{font-size:10px;color:#aeb5c0;margin:10px 0 6px}.mf-ts-uv{display:grid;grid-template-columns:1fr 1fr;gap:5px}.mf-ts-uv-field{display:grid;grid-template-columns:1fr 1fr;gap:5px;align-items:center}.mf-ts-uv-field span{font-size:8px;color:#737b87}.mf-ts-uv-field input{width:100%;height:27px;box-sizing:border-box;border:1px solid #333843;border-radius:4px;background:#111318;color:#d6dae0;padding:0 6px;font-size:9px}.mf-ts-uv-buttons{grid-column:1/-1;display:flex;gap:5px}@media(max-width:600px){.mf-ts-slot{align-items:flex-start}.mf-ts-actions{flex-direction:column}}`;document.head.appendChild(s)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initTextureSystem,{once:true});else initTextureSystem();
